# Generated by Django 4.0.1 on 2022-01-21 06:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Points',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('X', models.IntegerField()),
                ('Y', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='GIS',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Country', models.CharField(max_length=100)),
                ('Points', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.points')),
            ],
        ),
    ]
