# Generated by Django 4.0.1 on 2022-01-26 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gis',
            old_name='Points',
            new_name='name_id',
        ),
        migrations.RemoveField(
            model_name='points',
            name='name',
        ),
        migrations.AddField(
            model_name='gis',
            name='name',
            field=models.CharField(default='NoName', max_length=100),
        ),
        migrations.AlterField(
            model_name='points',
            name='X',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='points',
            name='Y',
            field=models.FloatField(),
        ),
    ]
