# Generated by Django 4.0.1 on 2022-01-26 14:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_rename_points_gis_name_id_remove_points_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gis',
            name='Country',
        ),
        migrations.RemoveField(
            model_name='gis',
            name='name_id',
        ),
        migrations.AddField(
            model_name='points',
            name='name_id',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='home.gis'),
        ),
    ]
