# Generated by Django 4.0.1 on 2022-01-27 06:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_remove_gis_country_remove_gis_name_id_points_name_id'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='GIS',
            new_name='UGS',
        ),
    ]
