# Generated by Django 4.0.1 on 2022-01-27 12:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_rename_gis_ugs'),
    ]

    operations = [
        migrations.CreateModel(
            name='UGS_names',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='points',
            name='name_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.ugs_names'),
        ),
        migrations.DeleteModel(
            name='UGS',
        ),
    ]
