# Generated by Django 4.0.1 on 2022-01-31 08:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_ugs_names_alter_points_name_id_delete_ugs'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Points',
            new_name='Points_out',
        ),
        migrations.CreateModel(
            name='Points_in',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('X', models.FloatField()),
                ('Y', models.FloatField()),
                ('name_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.ugs_names')),
            ],
        ),
    ]
