# Generated by Django 4.0.2 on 2022-02-21 06:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_rename_points_points_out_points_in'),
    ]

    operations = [
        migrations.RenameField(
            model_name='points_in',
            old_name='name_id',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='points_out',
            old_name='name_id',
            new_name='name',
        ),
    ]
