# Generated by Django 4.0.2 on 2022-02-21 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_ugs_settings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ugs_settings',
            name='volume_in',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='ugs_settings',
            name='volume_out',
            field=models.FloatField(),
        ),
    ]
