# Generated by Django 4.0.2 on 2022-02-21 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_alter_ugs_settings_volume_in_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ugs_settings',
            name='capacity',
            field=models.BigIntegerField(),
        ),
    ]
